### ISSUE TITLE
Reminder dates change by themselves to 1/1/1970

### ISSUE THREAD

**Issue by elbill** [globaleaks/whistleblowing-software#4121]
### What version of GlobaLeaks are you using?

4.15.6

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Some reminder dates with open status change by themselves to 1/1/1970. The default reminder interval is 90 days.

**Comment by evilaliv3** [comment]
Thank you @elbill 

You are right, we decided to reset the reminder date as soon that one recipient check the report since the reminder date, but instead of resetting it we are setting it to a wrong timing and so the reminder is remaining active.

I'm going to issue a patch and include it in a minor release for version 4.

**Comment by elbill** [comment]
Thanks.
what is the point of resetting the reminder date? What kind of reset are we
talking about (disable)?
If the recipient missed  their deadline, they check the report for what
needs to be done but may not take action immediately.
Then resetting can be confusing. I understand that people may not reset the
reminders but missing one may cause more problems.

Στις Κυρ 7 Ιουλ 2024 στις 10:28 μ.μ., ο/η Giovanni Pellerano <
***@***.***> έγραψε:

**Comment by evilaliv3** [comment]
Many clients of other community members got confused of receiving too many emails of reminder; this was reported for example to @larrykind and @gfraschini

For this reason we decided to disable the reminder automatically when a recipient access a report after the reminder date.

This behaviour is considered particular important when you have one recipient only taking care of the reports on behalf of a team. The typical user seems to prefer that the reminder is disabled as soon that they open the report since the reminder date passes.

**Comment by evilaliv3** [comment]
Closing the ticket since it has been addressed and the feature is now fully functional in current release 5.0.12
